### ISSUE TITLE
설치한 라이브러리를 검토한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#12]
## ⚠️Issue
- 설치한 라이브러리를 검토한다.

## ✏️Task
- 설치한 라이브러리를 검토한다.
  - [x] package.json의 dependencies와 devDependencies를 점검한다.
    - [x] 해당 관련 자료는 스터디 레포에 따로 올려 링크 첨부 예정
    > dependencies: 애플리케이션 실행 시 필요한 라이브러리들이 포함되어야 한다.
devDependencies: 개발, 빌드, 테스트 등의 과정에서만 필요한 라이브러리들이 포함되어야 한다.
  - [x] `tsconfig.json 파일에서 다음과 같은 경고` 를 확인한다. #11 
    - path 설정 후 경고 발생하지 않음, 오류 해결
  - [x] eslint와 prettier를 통합 설정 및 확인한다.
    - ~[ ] 환경 세팅 후 husky 라이브러리를 설치하고 설정한다.~
  - [x] Mocking을 하기위한 하위 디렉토링 생성
    - [x] Mocking을 실행할 json-server 라이브러릴 설치
    - [x] 실행및 test 완료

## 🗓Next Task
- 현재로는 husky라이브러리를 사용하는게 맞는지 조금은 의문이 든다. 따라서 재상의를 하고난 다음에 진행하는게 맞다고 판단.

**Comment by 4BFC** [comment]
🐞Bug report
- level: Warning
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.
```
위 해당 경고는 React 버전이 아닌 Create React App(CRA) 5.x 이후부터 발생한다.
CRA가 유지 관리되지 않으므로, 해당 문제는 향후 업데이트에서 해결될 가능성이 낮다. (아마도 최근에는 Next를 사용하고 React를 직접 webpack으로 필요한 플러그인들을 설치하고 있기 때문에 그럴 것이다. 추후에 스터디에서 시간이 된다면 `npm run eject`를 통해서 React의 webpack을 직접 열어보는 시간을 가져보면 좋을 듯 하다.)
따라서 해결 방법은 `@babel/plugin-proposal-private-property-in-object`를 수동으로 **devDependencies**에 추가하는 것이다.
- 최근에는 `@babel/plugin-proposal-private-property-in-object`보다 `npm install --save-dev @babel/plugin-transform-private-property-in-object`를 설치하라고 권장한다. 관련 문서와 레퍼런스는 [링크](https://stackoverflow.com/questions/76435306/babel-preset-react-app-is-importing-the-babel-plugin-proposal-private-propert "Warning Message: One of your dependencies, babel-preset-react-app, is importing the '@babel/plugin...'")를 통해서 확인이 가능하다.

**Comment by 4BFC** [comment]
🐞Error Report
- level: Warning (Terminal : Eslint Error)
```
  D:\<myWorkspace>\~\Ptory_Front\front\src\View\test.tsx
    1:1  error  Use const or class constructors instead of named functions 
   prefer-arrow/prefer-arrow-functions
  
  ✖ 1 problem (1 error, 0 warnings)
```
eslint를 적용하고 `npm run lint`로 수동으로 명령어를 사용해야 활성화 될 수 있게 코드를 변경하였다. 해당 Error는 eslint의 오류로 런타임과는 무관한 에러이다. 즉, 우리가 설정한 규칙에서 발생한 error이다. 따라서 `--fix`명령의 한계로 직접 문제가 있는 코드를 수정해야만 한다. 만약 자동완성이 수행이 된다면 좋겠지만 `workspace`를 활용하면서 확인 될 수 없는 패키지들간의 충돌로 보고 있다.

- 참고로 현재 자동 수정이 활성화가 안되는 상황이다. 명확한 에러가 발생하지는 않는다. 현재 추론으론 몇 Eslint와 Prettier 그리고 `.vscode/setting.json`간의 패키지, 코드들간의 충돌로 추론된다. 전역으로 설정한 `.eslintrc.cjs` 또한 front 디렉토리에서 활성화가 되지 않아 front에 직접 front 디렉토리에 `.eslintrc.cjs`를 생성하고 루트에 있는 `.eslintrc.cjs`를 `extends`해서 연결했다. 물론 workspace로 구성은 했지만 반은 workspace의 특성을 띄지만 일부 workspace 답지 않은 프로젝트다. 예를들면 package.json에 `"private":  true`와 같은 모노레포 형식이 없다. 결론적으로 각 디렉토리에는 `node_modules`가 존재해야하며 이로인해 발생하는 충돌일 가능성이 가장 크다. 따라서 `.vscode/setting.json`에 설정한 `eslint.workingDirectories`는 정상 동작을 할 수 없을 것으로 추측된다.
workspace가 곧 mono-repo는 아니다. 해당 [링크](https://velog.io/@k1my3ch4n/yarn-workspaces-%EB%A1%9C-monorepo%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0-2-prettier-eslint-%EC%84%A4%EC%A0%95 "yarn으로 mono-repo 구축하기")을 통해서 이상적인 mono-rep와 workspace의 모습을 조금은 들여다 볼 수 있다.
현재의 환경에서 이상적인 mono-rep와 workspace의 모습을 구현하려면 `Lerna`를 사용야한다. 해당 [링크](https://kdydesign.github.io/2020/08/27/mono-repo-lerna-example/) 를 통해서 확인 할 수 있다.
- 현재 문제점은 build를 했을 때 front에서 수행이 되어야하고 해당 front에 build된 파일만 CI/CD로 넘어가 동작해야한다. `vercel`에서 해당 build 파일을 지정할수 있는지가 조금은 의문이다.

👀정리
- mono-repo가 아니기에 발생하는 Eslint문제 (추측)
- `Lerna`로 전환하기에는 시간이 부족하다.
- 추후 build 과정에서 발생할 충돌과 문제들, 현재 workspace의 고질적 문제를 어떻게 극복해야하는가.
- @nyun-nye 현재의 문제 사항을 어떻게 해결 해야할지 같이 고민해보면 좋겠습니다.
