### ISSUE TITLE
디자인 시스템을 적용하고 환경을 초기화 한다.

### ISSUE THREAD

**Issue by nyun-nye** [p-factory/p-factory#14]
## ⚠️Issue
- 디자인 시스템을 적용한다.
- 환경을 초기화 한다.

## ✏️Task
- [x] 디자인 시스템을 적용한다.
  - [x] tawilwind.config.js에 전역변수로 디자인 시스템을 명시한다.
- [x] 환경을 초기화 한다.
  - [x] app.tsx, index.tsx를 중점으로 초기화 한다.
  - [x] app.css, index.css를 따로 초기화하지 않는다. (tailwind를 사용하기 때문)
- [x] react-router-dom을 설치한다.

## 🗓Next Task
-
