### ISSUE TITLE
적용된 디자인 시스템 TailwindCSS를 구체적으로 분리하고 리팩토링 한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#16]
## ⚠️Issue
- tailwind.config.js에 적용되어 있는 디자인 시스템을 `plugin` 방식으로 커스텀하고 현재 적용, tailwind에서 제공되고 있는 `utility first`에서 벗어나게 리팩토링 한다.
  - Utility First란 미리 세팅된 유틸리티 클래스를 활용하여 HTML코드 내에서 CSS를 적용시키는 것을 뜻 한다.

## ✏️Task
- [x] tailwind.config.js의 `plugin`을 커스텀한다.
  - [x] 디자인 시스템에 적용된 부부들을 tailwindcss 유틸리티 모듈 형식으로 나눈다.
  - [x] display를 통해서 중앙 정렬이 될 수 있는 tailwindcss 컴포넌트를 커스텀한다.
    - [x] 전체적인 영역에 적용될 display를 커스텀한다.
    - [x] 전체 영역 내부에 있는 부분을 위한 display를 커스텀한다.
      > 아래 코드는 예시입니다. 태그 네임 또한 예시입니다. 저희 프로젝트는 특별한 이유가 없다면 모두 div를 사용할 예정입니다.
      ```
          return (
            <container> <-- primary-flex
              <group> <-- sub-flex
              </group>
            </container>
          )
      ```
    - [x] a태그 span 태그와 같은 모든 속성들의 marin 값을 초기화 세팅을 한다.
- [x] 불필요한 코드와 파일들을 삭제한다.
- [x] 자동완성을 craco를 사용해서 webpack을 커스텀해서 eslint 우선 순위를 우리가 만든 eslintrc.cjs를 우선으로 둘 수 있게 한다.

## 🗓Next Task
-

**Comment by 4BFC** [comment]
- feature/12 브랜치에 있는 mocking을 업데이트 하지 않고 github에서 merge를 해서 아래와 같은 명령어로 특정 디렉토리를 가지고 왔습니다. 참고하시면 좋을 듯 합니다.
```
  git checkout feature/12 -- mocking
```

**Comment by 4BFC** [comment]
- App.test.tsx 파일은 삭제 했습니다. 해당 파일은 `jest`나 `React Testing Library`를 사용할 때 사용합니다. 본래에서는 `~.test.{js|jsx|ts|tsx|etc}`는 테스트 라이브러릴위한 네이밍이지만 현재 저희들의 Ground Rule에서는 다르게 사용될 것입니다. 따라, App.test.tsx 는 저희 프로젝트에서 `jest`나 `React Testing Library`를 사용하지 않기 때문에 삭제 했습니다. 아래는 삭제한 원문 코드입니다.
  ```
    import React from 'react';
    import { render, screen } from '@testing-library/react';
    import App from './App';
    
    test('renders learn react link', () => {
      render(<App />);
      const linkElement = screen.getByText(/learn react/i);
      expect(linkElement).toBeInTheDocument();
    });
  ```
