### ISSUE TITLE
Mocking을 할 수 있는 환경을 구현한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#18]
## ⚠️Issue
- Mocking을 할 수 있게 json-server를 단일이 아닌 병렬로 구현한다.
  - nodejs로 json-server를 커스텀한다.
  - Express는 사용하지 않는다.
- 주말간 zod, jsdoc을 사용하는 방법을 [Extra](https://github.com/Programming-Contents-List/TypeScript/issues/55 "코딩 스터디")에 정리해서 글을 PR을 작성한다.

## ✏️Task
- [x] Mocking을 할 수 있게 json-server를 단일이 아닌 병렬로 구현한다.
  - [x] nodejs로 json-server를 커스텀한다.
  - [x] Express는 사용하지 않는다.

## 🗓Next Task
- Mocking을 테스트하고 적용해본다.
- SWR과 tanstackQuery를 사용해서 Mocking API 통신 환경을 구현한다.
