### ISSUE TITLE
재활용 할수 있는 전체 컴포넌트를 구현한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#19]
## ⚠️Issue
- ~Login 페이지를 tailwind로 구현한다.~
- 재활용 할수 있는 전체 컴포넌트를 구현한다.

## ✏️Task
- ~[ ] Login 페이지를 tailwind로 구현한다.~
- ~[ ] margin-collapsing을 활용해서 코드를 겹침을 구현한다.~
- ~[ ] SignUp페이지를 tailwind로 구현한다.~
- [x]  재활용 할수 있는 전체 컴포넌트를 구현한다.
- [x] 내부에 컨텐츠를 넣을 수 있는 영역을 컴포넌트 porps로 받아 올 수 있게 설정한다.
  - [x] props에 height값과 width값을 입력할 수 있게 설정한다
  - [x] clamp를 사용한다.
  - [x] Zod를 설치하고 Zod로 데이터 검증을 수행할 수 있는 로직을 구현한다.

## 🗓Next Task
- ~각 팀원들의 페이지를 보고 컴포넌트로 분리한다.~

**Comment by 4BFC** [comment]
- 아래와 같은 방식으로 디테일하게 작업
  - width/hegiht 값을 정의하는 div
  - flex를 조절하는 div

**Comment by 4BFC** [comment]
- Tailwind CSS와 일반 CSS의 스타일 상속 및 우선순위와 관련되어서 동작이 다르게 된다. Tailwind CSS는 유틸리티 클래스가 기본적으로 높은 우선순위를 가지고 있다. 그래서 index.css에서 설정한 일반적인 CSS 스타일이 Tailwind의 클래스에 의해 덮어씌워지는 경우가 많다.
- 따라서 Tailwind CSS의 클래스를 사용하여 명시적으로 높이 값을 설정하거나 우선순위를 높이는 CSS를 사용하여 (!important), 기본 스타일이 덮어쓰이지 않도록 한다. 또는 Tailwind의 container 또는 h-screen 클래스 사용 권장 한다. 결론적으로 margin이나 padding으로 설정하는 것이 옳다고 판단 된다.

**Comment by 4BFC** [comment]
- container
  - container는 반응형 그리드 시스템과 중앙 정렬을 쉽게 설정하기 위해 만들어졌다. container를 사용할 때 px 단위로 계산해도 되지만 Tailwind의 반응형 브레이크포인트와 상대적인 단위를 사용하는 것이 권장된다. 따로 (학습이 필요)
- my/mx-auto
  - my/mx-auto로 전체 그리드의 중앙 정렬 방식 이를 사용하는 이유는 index.css가 후순위로 밀리면서 직접 적용해줘야 한다.

**Comment by 4BFC** [comment]
- 작업 방식 간략하게 요약
> 직접 정의는 clamp를 이용
  - root div에 중앙 정렬 적용(h-screen만 존재/w-full 없음, flex로 가운데 적용, container 적용)
  - 전체적인 레이아웃 구성(h,w/단위: %)
  - 세부적인 요소들 구성(padding 값으로 요소 크기 선정/ 단위: %)
  - 각 요소들 간격 조정(margin/단위: %)

**Comment by 4BFC** [comment]
앞으로 프로젝트의 TailwindCSS를 어떻게 사용하면 좋을지에 대한 독백
- 현재 가독성이 많이 떨어지고 React의 철학을 기반으로 Tailwind를 보았을 때 많이 난해하다. 가독성을 극복, 반응형의 한계를 극복 이 두가지를 고민하면서 프로젝트를 진행하고 있다. 분명 이둘은 중첩되는 공통 분모가 존재할 것이다. 물론 대형 프로젝트에서는 SASS와 Tailwind를 함께 사용한다.(카카오 같은 곳에서 말이다.) 미래의 방향성을 짚어볼 필요가 있지 않을까 한다.
