### ISSUE TITLE
디자인 시스템 적용 문제를 해결한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#21]
## ⚠️Issue
- 디자인 시스템 적용 과정에서 발생한 문제
  - 특정 넓이의 px 값 적용이 개발자들의 환경에 맞지 않는 크기로 인해 CSS overflow가 발생 이를 해결 하기 위해서 px값을 유지하면서 사용자들에게 어떻게 문제를 해결할지 논의한다.

## ✏️Task
- [x] 디자인 시스템의 단위를 고민해본다.
- [x] 현재 상황에서 해결 할 수 있는 해결 방안을 모색한다.
  - [x] px을 %로 계산할 수 있는 로직을 구현하다.
  - [x] 개발환경에 적용할 수 있는 임시적은 UI를 구현한다.

## 🗓Next Task
- 해당 이슈를 팀원과 논의한다.
