### ISSUE TITLE
Position 속성에 대해 알아본다.

### ISSUE THREAD

**Issue by nyun-nye** [p-factory/p-factory#24]
## ⚠️Issue
- Position 속성에 대해 알아본다.

## ✏️Task
- [x] Position 속성을 적용할 페이지를 제작한다.
  - [x] 기존 로그인 페이지와 동일한 페이지를 새로 만들어 코드를 수정해본다.
- [x] absolute와 fixed의 차이를 알아본다.
- [x] left, top의 단위를 변경해본다.

## 🗓Next Task
