### ISSUE TITLE
ver.0.0.2 디렉토리 구조를 구현해본다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#27]
## ⚠️Issue
- ver.0.0.2 디렉토리 구조를 구현해본다.
- 안정적인 구조를 위한 디렉토리 구조 구현
> release/ver.0.0.2으로 구조 구현

## ✏️Task
- [x] 모노레포로 구현 한다.
  - [x] pnpm packageManager로 적용한다.
  - [x] 해당 글을 분석해보고 연구해본다. : https://github.com/p-factory/p-factory/pull/13#issuecomment-2411408330
  - [x] 현재 node_modules가 왜 각기 디렉토리에 생성되는지 확인한다.
    - [x] 완변한 모노레포로 구성이 되지 않는 이유(CRA)
  - [x] eslint를 설정하고 test한다.
    - [x] overrides, extneds로 문제 해결( 둘의 차이 설명 필요 )
  - [x] 자동완성을 해결한다.
    - [x] VSC Extentions: run on save
- [ ]  Husky를 설정할지 고민해본다.

## 🗓Next Task
-

**Comment by 4BFC** [comment]
- 자동 수정을 run on save VSC Extentions를 통해서 해결 
![image](https://github.com/user-attachments/assets/4e7bb7fd-24a4-468f-a77e-abf9f6c3c795)
- VSCode 명령어 팔레트 (Ctrl + Shift + P)에서 "Preferences: Open Keyboard Shortcuts (JSON)"를 선택 선택 후 .vscode/tasks.json에 생성한 command label을 연결(`ctrl+alt++edit`이라는 의미로 단축키 `e`로 지정)
  ```
    {
      "key": "ctrl+alt+e",  // 원하는 단축키 지정
      "command": "workbench.action.tasks.runTask",
      "args": "Run ESLint Fix"  // task의 label과 동일하게 설정
    },
    {
      "key": "ctrl+alt+t",
      "command": "workbench.action.tasks.runTask",
      "args": "Run Echo"  // Run Echo 작업에 대한 단축키도 설정 가능
    }
  ```
