### ISSUE TITLE
디자인을 맞추기 위해 Template 컴포넌트의 구조를 수정한다.

### ISSUE THREAD

**Issue by nyun-nye** [p-factory/p-factory#40]
## ⚠️Issue
- 디자인을 맞추기 위해 Template 컴포넌트의 구조를 수정한다.

## ✏️Task
- [ ] 템플릿을 수정한다.
  - [x] [test/feature/29](https://github.com/p-factory/p-factory/tree/test/feature/29)를 받아와 중앙 정렬하는 코드를 살펴보고 이어서 작업한다.
  - [ ] 템플릿에 그림자 속성을 추가한다.
- [x] VocabularyBook 페이지의 background 요소가 전체 화면 크기에 변화가 있을 때 컨텐츠에 맞춰서 배치되지 않는 문제를 수정한다.

**Comment by nyun-nye** [comment]
더 명확해진 것 같습니다. 변경된 title로 pr도 작성하겠습니다!
