### ISSUE TITLE
develop 브렌치의 전체적인 기능을 점검한다.

### ISSUE THREAD

**Issue by 4BFC** [p-factory/p-factory#54]
## ⚠️Issue
- develop 브렌치의 전체적인 기능을 점검한다.

🔗[쿠키, 세션, 토큰, 캐시 그리고 CDN](https://hongong.hanbit.co.kr/%EC%99%84%EB%B2%BD-%EC%A0%95%EB%A6%AC-%EC%BF%A0%ED%82%A4-%EC%84%B8%EC%85%98-%ED%86%A0%ED%81%B0-%EC%BA%90%EC%8B%9C-%EA%B7%B8%EB%A6%AC%EA%B3%A0-cdn/)
🔗[쿠키, 세션, 토큰, 캐시](https://velog.io/@oplidote/%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-1-%EC%BF%A0%ED%82%A4-%EC%84%B8%EC%85%98-%ED%86%A0%ED%81%B0-%EC%BA%90%EC%8B%9C%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC-.-)
🔗[js-cookie 라이브러리](https://developer0809.tistory.com/49)

## ✏️Task
- [x] 페이지 연결
- [x] login 그림자 해결
  - [x] Template부분의 shadow의 위치값을 props로 분할한다.
  - [x] 로그인 후 발근되는 TOKEN을 어떻게 관리할지 학습하고 적용한다.
    - [x] js-cookie 라이브러리를 set과 get으로 관리한다.
- [x] 회원가입이 완료될 시 모달창을 구현한다.
- [x] 단어장페이지에서 재료 생성 버튼 클릭 시 모달창을 구현한다.

## 🗓Next Task
-
